import { useState, useEffect } from 'react';
import Sidebar from '../components/Sidebar';
import api from '../services/api';

export default function ReportsPage() {
    const [reports, setReports] = useState([]);
    const [selected, setSelected] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetch = async () => {
            try {
                const { data } = await api.get('/reports');
                setReports(data.reports || []);
            } catch (err) {
                console.error(err);
            } finally {
                setLoading(false);
            }
        };
        fetch();
    }, []);

    const viewReport = async (id) => {
        try {
            const { data } = await api.get(`/reports/${id}`);
            setSelected(data.report);
        } catch (err) {
            console.error(err);
        }
    };

    const getSeverityClass = (s) => `severity-badge severity-${s?.toLowerCase()}`;

    return (
        <div className="app-layout">
            <Sidebar />
            <main className="main-content">
                <div className="navbar"><h1>📝 Incident Reports</h1></div>

                {/* Report Viewer */}
                {selected && (
                    <div className="card" style={{ marginBottom: 24, borderColor: 'var(--accent-purple)' }}>
                        <div className="card-header">
                            <h3>{selected.reportTitle}</h3>
                            <button className="btn btn-secondary btn-sm" onClick={() => setSelected(null)}>✕ Close</button>
                        </div>
                        <div style={{ display: 'flex', gap: 16, marginBottom: 16, flexWrap: 'wrap' }}>
                            <div>
                                <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>Generated By: </span>
                                <span>{selected.generatedBy?.fullName || '—'}</span>
                            </div>
                            <div>
                                <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>Date: </span>
                                <span>{new Date(selected.createdAt).toLocaleString()}</span>
                            </div>
                            {selected.analysisId?.severity && (
                                <span className={getSeverityClass(selected.analysisId.severity)}>
                                    {selected.analysisId.severity}
                                </span>
                            )}
                        </div>
                        <div className="report-body">{selected.reportBody}</div>
                    </div>
                )}

                {/* Reports List */}
                <div className="card">
                    <div className="card-header"><h3>All Reports</h3></div>
                    {loading ? <div className="spinner" /> : reports.length === 0 ? (
                        <div className="empty-state">
                            <div className="empty-icon">📝</div>
                            <h3>No incident reports yet</h3>
                            <p>Generate reports from the Log Analysis page</p>
                        </div>
                    ) : (
                        <table className="data-table">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Title</th>
                                    <th>Severity</th>
                                    <th>Generated By</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {reports.map((r) => (
                                    <tr key={r._id}>
                                        <td style={{ fontSize: 12 }}>{new Date(r.createdAt).toLocaleString()}</td>
                                        <td>{r.reportTitle}</td>
                                        <td>
                                            {r.analysisId?.severity && (
                                                <span className={getSeverityClass(r.analysisId.severity)}>{r.analysisId.severity}</span>
                                            )}
                                        </td>
                                        <td>{r.generatedBy?.fullName || '—'}</td>
                                        <td>
                                            <button className="btn btn-primary btn-sm" onClick={() => viewReport(r._id)}>👁️ View</button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    )}
                </div>
            </main>
        </div>
    );
}
